### ISSUE TITLE
How to write test case use mock for bot reply contact messge?

### ISSUE THREAD

**Issue by chs97** [wechaty/wechaty-puppet-mock#37]
contact send a message to bot.  how to get the bot reply message?

```typescript
import test from 'tstest'
import sinon from 'sinon'
import { Wechaty } from 'wechaty'
import { PuppetMock, Mocker } from 'wechaty-puppet-mock'

test('reply', async (t) => {
  const sandbox = sinon.createSandbox()
  const mocker = new Mocker()
  const puppet = new PuppetMock({ mocker })
  const wechaty = new Wechaty({ puppet })
  const [user, contact] = mocker.createContacts(3)
  await wechaty.start()
  await mocker.login(user)

  // contact say something to user
  contact.say('Hello').to(user)
  // then
  wechaty.on('message', async (message) => {
    await message.say('world')
  })
  // how to write test case ? I want to get the reply message.
  sandbox.restore()
  await wechaty.stop()
})

```

**Comment by chs97** [comment]
@huan  please publish the last commit, wechaty-puppet-mock, I  see the mocker initial twice.

**Comment by huan** [comment]
It's great to see that you are trying to use the mocker to unit testing your bot!

### The Problem

How to receive the message from the bot with our mocker system?

### Solution

It's easy!

```ts
test('reply', async (t) => {
  const mocker = new Mocker()
  const puppet = new PuppetMock({ mocker })
  const wechaty = new Wechaty({ puppet })
  await wechaty.start()

  const [user, contact] = mocker.createContacts(3)
  await mocker.login(user)

  // ATTENTION: you need to register your listener before you say anything
  wechaty.on('message', async (message) => {
    await message.say('world')
  })

  // how to write test case ? I want to get the reply message.
  // SOLUTION:
  let reply
  contact.on('message', message => {
    reply = message.text()
  })

  // contact say something to user
  contact.say('Hello').to(user)

  await wechaty.stop()

  // FINALLY!
  assert(reply === 'world')
})
```

I hope this example can explain how to use the mocker system for you.

### A Complex Mocker Example

This weekend, I'm working on another complex unit test with the mocker and a text game: [Math Master](https://github.com/wechaty/wechaty-vorpal-contrib/blob/master/src/contrib/math_master.ts), which is one of our Wechaty Vorpal Extensions. 

The **Math Master** game is an interactive text game between the bot and users, the rule is very sample: the bot will ask math questions, and the user needs to answer it in a period of time. In order to test this game, we need the power of the mocker system, with more testing codes.

You can expect to read the unit tests for it this week, I'll notify you in this issue thread when I get it done.

### New Version Publish

About the fix: please wait for the v0.22.38 , I have just fixed the pack testing which blocked the module publish.

**Comment by chs97** [comment]
@huan ok thanks. the mocker object initial twice, so the Contact pool init with empty. the bot can't reply successfully

**Comment by huan** [comment]
As I mentioned in my last post: please use the  v0.22.38 to get a fixed version of the puppet mock.

**Comment by chs97** [comment]
This case can't work.
I have some questions.
1.  why emit to talker ? [code](https://github.com/wechaty/wechaty-puppet-mock/blob/master/src/mocker/mocker.ts#L303)
2. wechaty listened to the message, this message object, not mockMessage, [code](https://github.com/wechaty/wechaty/blob/master/src/wechaty.ts#L696)
look like will created a new Message object, not mock message.

**Comment by huan** [comment]
1. If you send a message to a friend, you and your friend will both received the message. That's why Wechaty will emit the message to talkers too because WeChat App will also display the message that you sent to you.
1. Wechaty will always work with the `Message`, on the other side, the Mocker will always work with the `MockMessage`.

**Comment by chs97** [comment]
You can run this case, I don't know why Message Object Created unlimited
```typescript

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}
test('reply', async (t) => {
  const mocker = new Mocker()
  const puppet = new PuppetMock({ mocker })
  const wechaty = new Wechaty({ puppet })
  await wechaty.start()

  const [user, contact] = mocker.createContacts(3)
  await mocker.login(user)

  // ATTENTION: you need to register your listener before you say anything
  wechaty.on('message', async (message) => {
    await message.say('world')
  })

  // how to write test case ? I want to get the reply message.
  // SOLUTION:
  let reply
  contact.on('message', message => {
    reply = message.text()
  })

  // contact say something to user
  contact.say('Hello').to(user)

  await sleep(1000)
  await wechaty.stop()
  // FINALLY!
  t.isEqual(reply, 'world')
})
```

**Comment by chs97** [comment]
Oh, I know，just because emit a message to himself?   wechaty say  ('world')  talker also receives the event?

**Comment by huan** [comment]
1. Yes, and No. Whether the message emitted by a bot will be received by itself will be dependent on the puppet implementation behavior.
1. My code is just a pseudo-code, it's just for an explanation purpose.
1. I can not understand what is `Message Object Created unlimited`, could you please explain it in details?

**Comment by chs97** [comment]
wechaty receives a message, and replies a message, then this message emits to (talker, room, listener) so wechaty receive this message again? then reply a message, once an once, is right? @huan

**Comment by huan** [comment]
We have a `createFixture` helper function now. 

See: https://github.com/wechaty/wechaty/issues/2022

**Comment by huan** [comment]
> wechaty receives a message and replies a message, then this message emits to (talker, room, listener) so wechaty receive this message again? then reply a message, once and once, is right? @huan

No, that will not and should not happen.

You should never reply what said by yourself, that's why we need to do the follow code logic:

```ts
wechaty.on('message', message => {
  if (message.self()) { return }
  // to reply the message after the above code
})
```

**Comment by chs97** [comment]
ok, it works. thanks.

**Comment by huan** [comment]
You are welcome.

**Comment by huan** [comment]
As I promised, here's the unit test for [Wechaty Vorpal](https://github.com/wechaty/wechaty-vorpal) Text Game: The [Math Master](https://github.com/wechaty/wechaty-vorpal-contrib/blob/master/src/contrib/math_master/math_master.ts), powered by the [Wechaty Mocker](https://github.com/wechaty/wechaty-puppet-mock/blob/master/src/mock/mocker.ts):

https://github.com/wechaty/wechaty-vorpal-contrib/blob/master/src/contrib/math_master/math_master.spec.ts
